---
on:
    push:
      branches:
      - main
      - maint/*
      tags:
      - '*'
    pull_request:
      branches:
      - main
      - maint/*

defaults:
    run:
        shell: bash


jobs:
    lazy-test:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            python-version: ['3.10', '3.11', '3.12']
        steps:
        - uses: actions/checkout@v4
          name: Set up Python ${{ matrix.python-version }}
        - uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install build dependencies
          run: python -m pip install --upgrade pip
        - name: Install task package
          run: pip install -e .[test]

        - name: Run the tests script as a smoke test.
          run: |
            python general_class_balancer/tests/random_example_test.py
            echo "Got exit code: $?"
            exit "$?"
